In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\archive\\phases.csv')

In [3]:
df1.head()

   phase_id                          phase_name
0         1         Phase 1: Avengers Assembled
1         2          Phase 2: Ultron Revolution
2         3              Phase 3: Infinity Saga
3         4            Phase 4: Multiverse Saga
4         5  Phase 5: Multiverse Saga Continues

In [4]:
df2 = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\archive\\public_response.csv')

In [6]:
df2.head()

,movie_id,movie_name,tomato_meter,audience_score,metacritical,cinema_score,domestic_ranking,world_wide_ranking,phase_id
0,1,Iron Man,94,91.0,79,A,89,190,1
1,2,The Incredible Hulk,67,70.0,61,A-,494,625,1
2,3,Iron Man 2,72,71.0,57,A,95,172,1
3,4,Thor,77,76.0,57,B+,280,290,1
4,5,Captain America: The First Avenger,79,75.0,66,A-,298,394,1

In [7]:
df3 = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\archive\\BoxOffice_Performance.csv')

In [8]:
df3.head()

,movie_id,movie_name,Phase_id,worldwide_box_office,domestic_box_office,international_box_office,opening_weekend,production_budget,worldwide_box_office_millions,domestic_box_office_millions,...,Domestic_vs_Budget_Percentage,Post_Opening_Weekend_Percentage,Domestic_Post_Opening_Percentage,Post_Opening_vs_Budget_Percentage,release_date,movie_duration,director,writer,producer,status
0,1,Iron Man,1,585171547,318604126,266567421,102118668,186000000,585.17M,318.60M,...,171.29,82.55,67.95,259.71,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Incredible Hulk,1,265573859,134806913,130766946,55414050,137500000,265.57M,134.81M,...,98.04,79.13,58.89,152.84,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iron Man 2,1,621156389,312433331,308723058,128122480,170000000,621.16M,312.43M,...,183.78,79.37,58.99,290.02,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Thor,1,449326618,181030624,268295994,65723338,150000000,449.33M,181.03M,...,120.69,85.37,63.69,255.74,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Captain America: The First Avenger,1,370569776,176654505,193915271,65058524,140000000,370.57M,176.65M,...,126.18,82.44,63.17,218.22,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df4 = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\archive\\marvel_movies.csv')

In [10]:
df4.head()

,movie_id,movie_name,release_date,movie_duration,director,writer,producer,status,phase_id
0,1,Iron Man,5/2/2008,126,Jon Favreau,Mark Fergus & Hawk Ostby and Art Marcum & Matt...,Avi Arad and Kevin Feige,Released,1
1,2,The Incredible Hulk,6/13/2008,112,Louis Leterrier,Zak Penn,"Avi Arad, Gale Anne Hurd, and Kevin Feige",Released,1
2,3,Iron Man 2,5/7/2010,124,Jon Favreau,Justin Theroux,Kevin Feige,Released,1
3,4,Thor,5/6/2011,113,Kenneth Branagh,Ashley Edward Miller & Zack Stentz and Don Payne,Kevin Feige,Released,1
4,5,Captain America: The First Avenger,7/22/2011,124,Joe Johnston,Christopher Markus & Stephen McFeely,Kevin Feige,Released,1

In [11]:
df5 = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\archive\\list_all_characters.csv')

In [12]:
df5.head()

,id,film_id,film,character_id,Characters,Actor,phase_id
0,1,1,Iron Man,1,"Robert Downey ,Jr.",Tony Stark/Iron Man,1
1,2,1,Iron Man,2,Terrence Howard,Rhodey,1
2,3,1,Iron Man,3,Jeff Bridges,Obadiah Stane,1
3,4,1,Iron Man,4,Gwyneth Paltrow,"Virginia ""Pepper"" Potts",1
4,5,2,The Incredible Hulk,5,Edward Norton,Bruce Banner,1

In [13]:
df1.isnull().sum()

phase_id      0
phase_name    0
dtype: int64

In [14]:
df2.isnull().sum()

movie_id              0
movie_name            0
tomato_meter          0
audience_score        8
metacritical          0
cinema_score          0
domestic_ranking      0
world_wide_ranking    0
phase_id              0
dtype: int64

In [15]:
df3.isnull().sum()

movie_id                                   0
movie_name                                 0
Phase_id                                   0
worldwide_box_office                       0
domestic_box_office                        0
international_box_office                   0
opening_weekend                            0
production_budget                          0
worldwide_box_office_millions              0
domestic_box_office_millions               0
international_box_office_millions          0
opening_weekend_millions                   0
production_budget_millions                 0
Budget_Percentage                          0
Opening_Weekend_Gross_Percentage           0
Domestic_Gross_Percentage                  0
International_Gross_Percentage             0
Budget_Opening_Weekend_Percentage          0
Budget_Recovered_Percentage                0
International_Collection_Percentage        0
International_vs_Budget_Percentage         0
Opening_Weekend_vs_Domestic_Percentage     0
Domestic_vs_Budget_Percentage              0
Post_Opening_Weekend_Percentage            0
Domestic_Post_Opening_Percentage           0
Post_Opening_vs_Budget_Percentage          0
release_date                              35
movie_duration                            35
director                                  35
writer                                    35
producer                                  35
status                                    35
dtype: int64

In [16]:
df4.isnull().sum()

movie_id          0
movie_name        0
release_date      0
movie_duration    0
director          0
writer            0
producer          0
status            0
phase_id          0
dtype: int64

In [17]:
df5.isnull().sum()

id              0
film_id         0
film            0
character_id    0
Characters      2
Actor           2
phase_id        0
dtype: int64

In [23]:
df2.dtypes

movie_id                int64
movie_name             object
tomato_meter            int64
audience_score        float64
metacritical            int64
cinema_score           object
domestic_ranking        int64
world_wide_ranking      int64
phase_id                int64
dtype: object

In [25]:
dl = pd.DataFrame({
    'A': ['John', 'Boby', 'Mina', 'Peter', 'Nicky'],
    'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'],
    'C': [27, 23, 21, 23, 24]
})
table = pd.pivot_table(dl, values='C', index='C', columns='B', aggfunc='sum')
print(table)

B  Graduate Masters
C
21     Mina     NaN
23     Boby   Peter
24    Nicky     NaN
27      NaN    John

In [30]:
print(df2['metacritical'].ndim)

1

In [32]:
print(df2.columns.tolist())
print(df2.columns[df2.columns == 'metacritical'])
print(df2.columns.duplicated().any())

['movie_id', 'movie_name', 'tomato_meter', 'audience_score', 'metacritical', 'cinema_score', 'domestic_ranking', 'world_wide_ranking', 'phase_id']
Index(['metacritical'], dtype='object')
False

In [35]:
sample_pivot = pd.pivot_table(
    df2,
    index='metacritical',
    columns='movie_id',
    aggfunc='size',
    fill_value=0
)
print(sample_pivot)

movie_id      1   2   3   4   5   6   7   8   9   10  ...  26  27  28  29  30  \
metacritical                                          ...
42             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
48             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
50             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
52             0   0   0   0   0   0   0   0   0   0  ...   1   0   0   0   0
54             0   0   0   0   0   0   0   1   0   0  ...   0   0   0   0   0
56             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
57             0   0   1   1   0   0   0   0   0   0  ...   0   0   0   1   0
60             0   0   0   0   0   0   0   0   0   0  ...   0   0   1   0   0
61             0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
62             0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0
64             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
66             0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0
67             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1
68             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
69             0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0
70             0   0   0   0   0   0   0   0   1   0  ...   0   0   0   0   0
71             0   0   0   0   0   0   0   0   0   0  ...   0   1   0   0   0
72             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
73             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
74             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
75             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
76             0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0
78             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
79             1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0
88             0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0

movie_id      31  32  33  34  35
metacritical
42             0   0   0   0   1
48             1   0   0   0   0
50             0   0   1   0   0
52             0   0   0   0   0
54             0   0   0   0   0
56             0   0   0   1   0
57             0   0   0   0   0
60             0   0   0   0   0
61             0   0   0   0   0
62             0   0   0   0   0
64             0   1   0   0   0
66             0   0   0   0   0
67             0   0   0   0   0
68             0   0   0   0   0
69             0   0   0   0   0
70             0   0   0   0   0
71             0   0   0   0   0
72             0   0   0   0   0
73             0   0   0   0   0
74             0   0   0   0   0
75             0   0   0   0   0
76             0   0   0   0   0
78             0   0   0   0   0
79             0   0   0   0   0
88             0   0   0   0   0

[25 rows x 35 columns]

In [36]:
df = pd.merge(df2, df3, on='movie_id')

In [37]:
df.head()

,movie_id,movie_name_x,tomato_meter,audience_score,metacritical,cinema_score,domestic_ranking,world_wide_ranking,phase_id,movie_name_y,...,Domestic_vs_Budget_Percentage,Post_Opening_Weekend_Percentage,Domestic_Post_Opening_Percentage,Post_Opening_vs_Budget_Percentage,release_date,movie_duration,director,writer,producer,status
0,1,Iron Man,94,91.0,79,A,89,190,1,Iron Man,...,171.29,82.55,67.95,259.71,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Incredible Hulk,67,70.0,61,A-,494,625,1,The Incredible Hulk,...,98.04,79.13,58.89,152.84,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iron Man 2,72,71.0,57,A,95,172,1,Iron Man 2,...,183.78,79.37,58.99,290.02,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Thor,77,76.0,57,B+,280,290,1,Thor,...,120.69,85.37,63.69,255.74,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Captain America: The First Avenger,79,75.0,66,A-,298,394,1,Captain America: The First Avenger,...,126.18,82.44,63.17,218.22,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df.drop(columns=['metacritical', 'cinema_score', 'domestic_ranking','world_wide_ranking'], inplace=True)

In [39]:
df.head()

,movie_id,movie_name_x,tomato_meter,audience_score,phase_id,movie_name_y,Phase_id,worldwide_box_office,domestic_box_office,international_box_office,...,Domestic_vs_Budget_Percentage,Post_Opening_Weekend_Percentage,Domestic_Post_Opening_Percentage,Post_Opening_vs_Budget_Percentage,release_date,movie_duration,director,writer,producer,status
0,1,Iron Man,94,91.0,1,Iron Man,1,585171547,318604126,266567421,...,171.29,82.55,67.95,259.71,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Incredible Hulk,67,70.0,1,The Incredible Hulk,1,265573859,134806913,130766946,...,98.04,79.13,58.89,152.84,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iron Man 2,72,71.0,1,Iron Man 2,1,621156389,312433331,308723058,...,183.78,79.37,58.99,290.02,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Thor,77,76.0,1,Thor,1,449326618,181030624,268295994,...,120.69,85.37,63.69,255.74,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Captain America: The First Avenger,79,75.0,1,Captain America: The First Avenger,1,370569776,176654505,193915271,...,126.18,82.44,63.17,218.22,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df.drop(columns=['domestic_box_office', 'international_box_office', 'Domestic_vs_Budget_Percentage','Post_Opening_Weekend_Percentage'], inplace=True)

In [41]:
df.head()

,movie_id,movie_name_x,tomato_meter,audience_score,phase_id,movie_name_y,Phase_id,worldwide_box_office,opening_weekend,production_budget,...,International_vs_Budget_Percentage,Opening_Weekend_vs_Domestic_Percentage,Domestic_Post_Opening_Percentage,Post_Opening_vs_Budget_Percentage,release_date,movie_duration,director,writer,producer,status
0,1,Iron Man,94,91.0,1,Iron Man,1,585171547,102118668,186000000,...,143.32,32.05,67.95,259.71,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Incredible Hulk,67,70.0,1,The Incredible Hulk,1,265573859,55414050,137500000,...,95.10,41.11,58.89,152.84,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iron Man 2,72,71.0,1,Iron Man 2,1,621156389,128122480,170000000,...,181.60,41.01,58.99,290.02,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Thor,77,76.0,1,Thor,1,449326618,65723338,150000000,...,178.86,36.31,63.69,255.74,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Captain America: The First Avenger,79,75.0,1,Captain America: The First Avenger,1,370569776,65058524,140000000,...,138.51,36.83,63.17,218.22,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.rename(columns={'movie_name_x': 'movie_name'}, inplace=True)
df.head()

,movie_id,movie_name,tomato_meter,audience_score,phase_id,movie_name_y,Phase_id,worldwide_box_office,opening_weekend,production_budget,...,International_vs_Budget_Percentage,Opening_Weekend_vs_Domestic_Percentage,Domestic_Post_Opening_Percentage,Post_Opening_vs_Budget_Percentage,release_date,movie_duration,director,writer,producer,status
0,1,Iron Man,94,91.0,1,Iron Man,1,585171547,102118668,186000000,...,143.32,32.05,67.95,259.71,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Incredible Hulk,67,70.0,1,The Incredible Hulk,1,265573859,55414050,137500000,...,95.10,41.11,58.89,152.84,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iron Man 2,72,71.0,1,Iron Man 2,1,621156389,128122480,170000000,...,181.60,41.01,58.99,290.02,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Thor,77,76.0,1,Thor,1,449326618,65723338,150000000,...,178.86,36.31,63.69,255.74,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Captain America: The First Avenger,79,75.0,1,Captain America: The First Avenger,1,370569776,65058524,140000000,...,138.51,36.83,63.17,218.22,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df6 = pd.merge(df1, df2, on='phase_id', how='inner')