In [60]:
import pandas as pd

In [61]:
df = pd.read_csv('C:\\Users\\Thinkbiz\\Python AI training\\Week 6\\imdb_top_1000.csv')

In [62]:
df.head

<bound method NDFrame.head of                                            Poster_Link  \
0    https://m.media-amazon.com/images/M/MV5BMDFkYT...
1    https://m.media-amazon.com/images/M/MV5BM2MyNj...
2    https://m.media-amazon.com/images/M/MV5BMTMxNT...
3    https://m.media-amazon.com/images/M/MV5BMWMwMG...
4    https://m.media-amazon.com/images/M/MV5BMWU4N2...
..                                                 ...
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...
997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min
1               The Godfather          1972           A  175 min
2             The Dark Knight          2008          UA  152 min
3      The Godfather: Part II          1974           A  202 min
4                12 Angry Men          1957           U   96 min
..                        ...           ...         ...      ...
995    Breakfast at Tiffany's          1961           A  115 min
996                     Giant          1956           G  201 min
997     From Here to Eternity          1953      Passed  118 min
998                  Lifeboat          1944         NaN   97 min
999              The 39 Steps          1935         NaN   86 min

                        Genre  IMDB_Rating  \
0                       Drama          9.3
1                Crime, Drama          9.2
2        Action, Crime, Drama          9.0
3                Crime, Drama          9.0
4                Crime, Drama          9.0
..                        ...          ...
995    Comedy, Drama, Romance          7.6
996            Drama, Western          7.6
997       Drama, Romance, War          7.6
998                Drama, War          7.6
999  Crime, Mystery, Thriller          7.6

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0
1    An organized crime dynasty's aging patriarch t...       100.0
2    When the menace known as the Joker wreaks havo...        84.0
3    The early life and career of Vito Corleone in ...        90.0
4    A jury holdout attempts to prevent a miscarria...        96.0
..                                                 ...         ...
995  A young New York socialite becomes interested ...        76.0
996  Sprawling epic covering the life of a Texas ca...        84.0
997  In Hawaii in 1941, a private is cruelly punish...        85.0
998  Several survivors of a torpedoed merchant ship...        78.0
999  A man in London tries to help a counter-espion...        93.0

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman
1    Francis Ford Coppola      Marlon Brando          Al Pacino
2       Christopher Nolan     Christian Bale       Heath Ledger
3    Francis Ford Coppola          Al Pacino     Robert De Niro
4            Sidney Lumet        Henry Fonda        Lee J. Cobb
..                    ...                ...                ...
995         Blake Edwards     Audrey Hepburn     George Peppard
996        George Stevens   Elizabeth Taylor        Rock Hudson
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll

              Star3           Star4  No_of_Votes         Gross
0        Bob Gunton  William Sadler      2343110   2,83,41,469
1        James Caan    Diane Keaton      1620367  13,49,66,411
2     Aaron Eckhart   Michael Caine      2303232  53,48,58,444
3     Robert Duvall    Diane Keaton      1129952   5,73,00,000
4     Martin Balsam    John Fiedler       689845     43,60,000
..              ...             ...          ...           ...
995   Patricia Neal     Buddy Ebsen       166544           NaN
996      James Dean   Carroll Baker        34075           NaN
997    Deborah Kerr      Donna Reed        43374   3,05,00,000
998   Walter Slezak  William Bendix        26471           NaN
999  Lucie Mannheim  Godfrey Tearle        51853           NaN

[1000 rows x 16 columns]>

In [63]:
print(df.head(5))

                                         Poster_Link  \
0  https://m.media-amazon.com/images/M/MV5BMDFkYT...
1  https://m.media-amazon.com/images/M/MV5BM2MyNj...
2  https://m.media-amazon.com/images/M/MV5BMTMxNT...
3  https://m.media-amazon.com/images/M/MV5BMWMwMG...
4  https://m.media-amazon.com/images/M/MV5BMWU4N2...

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min
1             The Godfather          1972           A  175 min
2           The Dark Knight          2008          UA  152 min
3    The Godfather: Part II          1974           A  202 min
4              12 Angry Men          1957           U   96 min

                  Genre  IMDB_Rating  \
0                 Drama          9.3
1          Crime, Drama          9.2
2  Action, Crime, Drama          9.0
3          Crime, Drama          9.0
4          Crime, Drama          9.0

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0
1  An organized crime dynasty's aging patriarch t...       100.0
2  When the menace known as the Joker wreaks havo...        84.0
3  The early life and career of Vito Corleone in ...        90.0
4  A jury holdout attempts to prevent a miscarria...        96.0

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam

            Star4  No_of_Votes         Gross
0  William Sadler      2343110   2,83,41,469
1    Diane Keaton      1620367  13,49,66,411
2   Michael Caine      2303232  53,48,58,444
3    Diane Keaton      1129952   5,73,00,000
4    John Fiedler       689845     43,60,000

In [64]:
df.isnull()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
999,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [65]:
df.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [66]:
 #df.dropna({"Series_Title"}(inplace = True))

In [67]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB
None

In [68]:
df['Series_Title'] = df['Series_Title'].astype('str')

In [69]:
df.dropna(subset=['Series_Title'])

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"3,05,00,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [70]:
df.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [71]:
df = df[df['Meta_score'].notna() & (df['Meta_score'] != "")]

In [72]:
df.isnull().sum()

Poster_Link       0
Series_Title      0
Released_Year     0
Certificate      56
Runtime           0
Genre             0
IMDB_Rating       0
Overview          0
Meta_score        0
Director          0
Star1             0
Star2             0
Star3             0
Star4             0
No_of_Votes       0
Gross            93
dtype: int64

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.iloc[0].Genre

'Drama'

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    843 non-null    object
 1   Series_Title   843 non-null    object
 2   Released_Year  843 non-null    object
 3   Certificate    787 non-null    object
 4   Runtime        843 non-null    object
 5   Genre          843 non-null    object
 6   IMDB_Rating    843 non-null    float64
 7   Overview       843 non-null    object
 8   Meta_score     843 non-null    float64
 9   Director       843 non-null    object
 10  Star1          843 non-null    object
 11  Star2          843 non-null    object
 12  Star3          843 non-null    object
 13  Star4          843 non-null    object
 14  No_of_Votes    843 non-null    int64
 15  Gross          750 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 112.0+ KB

In [76]:
df.isnull().sum()

Poster_Link       0
Series_Title      0
Released_Year     0
Certificate      56
Runtime           0
Genre             0
IMDB_Rating       0
Overview          0
Meta_score        0
Director          0
Star1             0
Star2             0
Star3             0
Star4             0
No_of_Votes       0
Gross            93
dtype: int64

In [77]:
df['Star1'] = df['Star1'].astype('str')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2869888936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Star1'] = df['Star1'].astype('str')

In [78]:
df['Star2'] = df['Star2'].astype('str')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2025471744.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Star2'] = df['Star2'].astype('str')

In [79]:
df['Star3'] = df['Star3'].astype('str')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2636463503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Star3'] = df['Star3'].astype('str')

In [80]:
df['Star_Cast'] = df[['Star1','Star2','Star3','Star4']].apply(
    lambda row: ', '.join([str(x).strip() for x in row if pd.notna(x) and str(x).strip() != '']),
    axis=1
)

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\4034393201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Star_Cast'] = df[['Star1','Star2','Star3','Star4']].apply(

In [81]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Star_Cast
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ..."

In [82]:
df.drop(columns=['Star1', 'Star2', 'Star3'], inplace=True)

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\1635027921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Star1', 'Star2', 'Star3'], inplace=True)

In [83]:
df.drop(columns=['Star4'], inplace=True)

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2299030171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Star4'], inplace=True)

In [84]:
# df['Star_Cast'] = df[['Star_Cast','Star4']].apply(
#     lambda row: ', '.join([str(x).strip() for x in row if pd.notna(x) and str(x).strip() != '']),
#     axis=1
#

In [85]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ..."

In [86]:
df['Certificate'] = df['Certificate'].astype('str')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\1489420760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Certificate'] = df['Certificate'].astype('str')

In [87]:
top = df.dropna(subset=['Series_Title', 'IMDB_Rating']).loc[(df['No_of_Votes'] >= 5000) & (df['IMDB_Rating'] >= 5.0)].sort_values(['IMDB_Rating', 'No_of_Votes'], ascending=[False, False]).head(20)

In [88]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ..."

In [89]:
df.groupby('Series_Title')
print(df.groupby('Series_Title').groups)

{'(500) Days of Summer': [754], '12 Angry Men': [4], '12 Years a Slave': [215], '1917': [84], '2001: A Space Odyssey': [114], '21 Grams': [938], '25th Hour': [941], '28 Days Later...': [943], '3 Idiots': [64], '300': [928], '3:10 to Yuma': [774], '4 luni, 3 saptamâni si 2 zile': [492], '50/50': [907], '8½': [432], 'A Beautiful Mind': [159], 'A Bronx Tale': [664], 'A Christmas Story': [531], 'A Clockwork Orange': [113], 'A Few Good Men': [824], 'A Hard Day's Night': [994], 'A Little Princess': [813], 'A Man for All Seasons': [858], 'A Star Is Born': [903], 'A Streetcar Named Desire': [447], 'About Time': [593], 'Ace in the Hole': [307], 'Adams æbler': [630], 'Adaptation.': [789], 'After Hours': [836], 'Ah-ga-ssi': [199], 'Airplane!': [842], 'Aladdin': [399], 'Alien': [75], 'Aliens': [106], 'All About Eve': [190], 'All Quiet on the Western Front': [461], 'All That Jazz': [534], 'All the President's Men': [536], 'Almost Famous': [514], 'Amadeus': [107], 'American Beauty': [98], 'American Gangster': [622], 'American History X': [40], 'American Psycho': [953], 'Amores perros': [244], 'Amour': [483], 'Amélie': [95], 'Anatomy of a Murder': [437], 'Ang-ma-reul bo-at-da': [602], 'Annie Hall': [414], 'Apocalypse Now': [74], 'Apocalypto': [625], 'Apollo 13': [966], 'Argo': [753], 'Arrival': [476], 'As Good as It Gets': [806], 'Atonement': [620], 'Au revoir les enfants': [408], 'Auf der anderen Seite': [619], 'Avatar': [623], 'Avengers: Endgame': [59], 'Avengers: Infinity War': [60], 'Awakenings': [671], 'Baby Driver': [888], 'Bacheha-Ye aseman': [100], 'Back to the Future': [47], 'Back to the Future Part II': [675], 'Badlands': [696], 'Barry Lyndon': [281], 'Barton Fink': [826], 'Batman Begins': [155], 'Batoru rowaiaru': [944], 'Beasts of No Nation': [747], 'Beauty and the Beast': [401], 'Before Midnight': [478], 'Before Sunrise': [259], 'Before Sunset': [237], 'Being John Malkovich': [805], 'Being There': [413], 'Ben-Hur': [300], 'Big Fish': [377], 'Big Hero 6': [592], 'Billy Elliot': [793], 'Bin-jip': [363], 'Bir Zamanlar Anadolu'da': [480], 'Birdman or (The Unexpected Virtue of Ignorance)': [733], 'Black Hawk Down': [790], 'Black Swan': [355], 'Blade Runner': [275], 'Blade Runner 2049': [340], 'Blazing Saddles': [848], 'Blood Diamond': [361], 'Blood Simple': [980], 'Blow': [949], 'Blowup': [993], 'Blue Velvet': [834], 'Bohemian Rhapsody': [342], 'Boksuneun naui geot': [939], 'Bom Yeoareum Gaeul Gyeoul Geurigo Bom': [371], 'Bonnie and Clyde': [702], ...}

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    843 non-null    object
 1   Series_Title   843 non-null    object
 2   Released_Year  843 non-null    object
 3   Certificate    843 non-null    object
 4   Runtime        843 non-null    object
 5   Genre          843 non-null    object
 6   IMDB_Rating    843 non-null    float64
 7   Overview       843 non-null    object
 8   Meta_score     843 non-null    float64
 9   Director       843 non-null    object
 10  No_of_Votes    843 non-null    int64
 11  Gross          750 non-null    object
 12  Star_Cast      843 non-null    object
dtypes: float64(2), int64(1), object(10)
memory usage: 92.2+ KB

In [91]:
df.aggregate({"No_of_Votes":['sum']})

     No_of_Votes
sum    264016757

In [92]:
df.aggregate({"No_of_Votes":['min']})

     No_of_Votes
min        25198

In [93]:
mappings = {
    'A': 'Adult',}

In [94]:
df['type_name'] = df['Certificate'].map(mappings)

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2156658929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type_name'] = df['Certificate'].map(mappings)

In [95]:
print(df['type_name'])

0      Adult
1      Adult
2        NaN
3      Adult
4        NaN
       ...
995    Adult
996      NaN
997      NaN
998      NaN
999      NaN
Name: type_name, Length: 843, dtype: object

In [96]:
import datetime

In [97]:
from datetime import date

In [98]:

# Creating a Timestamp object
timestamp = pd.Timestamp('2023-10-04 15:30:00')

# Extracting the year from the Timestamp
year = timestamp.year

# Printing the extracted year
print(year)

# Extracting the month from the Timestamp
month = timestamp.month

# Printing the extracted month
print(month)

# Extracting the day from the Timestamp
day = timestamp.day

# Printing the extracted day
print(day)

2023
10
4

In [99]:
# Extracting the hour from the Timestamp
hour = timestamp.hour

# Printing the extracted hour
print(hour)

# Extracting the minute from the Timestamp
minute = timestamp.minute

# Printing the extracted minute
print(minute)
# Extracting the weekday from the Timestamp
weekday = timestamp.weekday()

# Printing the extracted weekday
print(weekday)

# Extracting the quarter from the Timestamp
quarter = timestamp.quarter

# Printing the extracted quarter
print(quarter)

15
30
2
4

In [100]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast,type_name
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Adult
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke...",Adult
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M...",NaN
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian...",Adult
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",NaN

In [102]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast,type_name
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Adult
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke...",Adult
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M...",NaN
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian...",Adult
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",NaN

In [103]:
df.dtypes

Poster_Link       object
Series_Title      object
Released_Year     object
Certificate       object
Runtime           object
Genre             object
IMDB_Rating      float64
Overview          object
Meta_score       float64
Director          object
No_of_Votes        int64
Gross             object
Star_Cast         object
type_name         object
dtype: object

In [106]:
df["Runtime"] = df["Runtime"].str.replace("min", "", regex=True).astype(float)

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\562936487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Runtime"] = df["Runtime"].str.replace("min", "", regex=True).astype(float)

In [107]:
df.dtypes

Poster_Link       object
Series_Title      object
Released_Year     object
Certificate       object
Runtime          float64
Genre             object
IMDB_Rating      float64
Overview          object
Meta_score       float64
Director          object
No_of_Votes        int64
Gross             object
Star_Cast         object
type_name         object
dtype: object

In [108]:
df.head(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast,type_name
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142.0,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Adult
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175.0,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke...",Adult
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152.0,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M...",NaN
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202.0,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian...",Adult
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96.0,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",NaN

In [109]:
df['Runtime'] = df['Runtime'].astype('int')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\3208983419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Runtime'] = df['Runtime'].astype('int')

In [110]:
df.head(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast,type_name
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Adult
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke...",Adult
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"53,48,58,444","Christian Bale, Heath Ledger, Aaron Eckhart, M...",NaN
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"5,73,00,000","Al Pacino, Robert De Niro, Robert Duvall, Dian...",Adult
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"43,60,000","Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",NaN

In [112]:
df['total_time'] = pd.to_timedelta(df['Runtime'], unit='m').astype(str).str.replace('0 days ', '')

C:\Users\Thinkbiz\AppData\Local\Temp\ipykernel_2548\2118302867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_time'] = pd.to_timedelta(df['Runtime'], unit='m').astype(str).str.replace('0 days ', '')

In [114]:
print(df[['Runtime', 'total_time']])

     Runtime total_time
0        142   02:22:00
1        175   02:55:00
2        152   02:32:00
3        202   03:22:00
4         96   01:36:00
..       ...        ...
995      115   01:55:00
996      201   03:21:00
997      118   01:58:00
998       97   01:37:00
999       86   01:26:00

[843 rows x 2 columns]

In [115]:
df.head(2)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,Gross,Star_Cast,type_name,total_time
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"2,83,41,469","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Adult,02:22:00
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"13,49,66,411","Marlon Brando, Al Pacino, James Caan, Diane Ke...",Adult,02:55:00